import {
  AlertTriangle,
  ArrowRight,
  Bed,
  CalendarCheck2,
  Check,
  ChevronLeft,
  ChevronRight,
  CircuitBoardIcon,
  Command,
  Container,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Layers2,
  LayoutDashboardIcon,
  Loader2,
  LogIn,
  LucideIcon,
  LucideProps,
  LucideShoppingBag,
  Map,
  MapPinHouse,
  MessagesSquare,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  Share2,
  Sheet,
  SunMedium,
  Ticket,
  Trash,
  Twitter,
  User,
  UserCircle2Icon,
  UserPen,
  UserX2Icon,
  Waypoints,
  X
} from "lucide-react";
import {
  GoogleOriginal,
  FacebookOriginal,
  GithubOriginal
} from "devicons-react";
export type Icon = LucideIcon;
import { FaTrainSubway } from "react-icons/fa6";
export const Icons = {
  dashboard: LayoutDashboardIcon,
  logo: Command,
  login: LogIn,
  close: X,
  product: LucideShoppingBag,
  spinner: Loader2,
  kanban: CircuitBoardIcon,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  employee: UserX2Icon,
  post: FileText,
  page: File,
  userPen: UserPen,
  user2: UserCircle2Icon,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  chats: MessagesSquare,
  google: GoogleOriginal,
  facebook: FacebookOriginal,
  gitHub: GithubOriginal,
  twitter: Twitter,
  check: Check,
  train: FaTrainSubway,
  plus: Plus,
  sheet: Sheet,
  carriage: Container,
  type: Layers2,
  seat: Bed,
  map: Map,
  station: MapPinHouse,
  network: Share2,
  journey: Waypoints,
  ticket: Ticket,
  booking: CalendarCheck2
};
